# Generated by Django 5.1.2 on 2024-11-08 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=50)),
                ('premature_birth', models.CharField(max_length=50)),
                ('lifting_head_month', models.IntegerField()),
                ('rolling_over_month', models.IntegerField()),
                ('sitting_up_month', models.IntegerField()),
                ('crawling_month', models.IntegerField()),
                ('standing_with_support_month', models.IntegerField()),
                ('standing_individually_month', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_milestones', to='patientreg.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PregnancyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_level', models.CharField(max_length=50)),
                ('abortion_history', models.CharField(max_length=50)),
                ('bmi', models.CharField(max_length=50)),
                ('blood_pressure', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancy_details', to='patientreg.patient')),
            ],
        ),
    ]
